// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AmanTaskAPI.Models;

public partial class AmanTaskContext : DbContext
{
    public AmanTaskContext()
    {
    }

    public AmanTaskContext(DbContextOptions<AmanTaskContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Mail> Mail { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Receiver> Receivers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Mail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Mail__3213E83FB65A4398");

            entity.Property(e => e.Data).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Message).WithMany(p => p.Mail)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Mail_Message");

            entity.HasOne(d => d.Receiver).WithMany(p => p.Mail)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Mail_Receiver");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Message_1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}