// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AmanTaskAPI.Models;

public partial class Mail
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Data { get; set; }

    public int ReceiverId { get; set; }

    public int MessageId { get; set; }

    [ForeignKey("MessageId")]
    [InverseProperty("Mail")]
    public virtual Message Message { get; set; }

    [ForeignKey("ReceiverId")]
    [InverseProperty("Mail")]
    public virtual Receiver Receiver { get; set; }
}