// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AmanTaskAPI.Models;

[Table("Message")]
public partial class Message
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Text { get; set; }

    [Required]
    public string Subject { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Message")]
    public virtual ICollection<Mail> Mail { get; set; } = new List<Mail>();
}